/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog  
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.api;

import java.util.Date;
import io.swagger.model.ErrorRepresentation;
import io.swagger.model.ProductOfferingQualification;
import io.swagger.model.ProductOfferingQualificationCreate;
import io.swagger.model.ProductOfferingQualificationFind;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * MEF LSO Sonata
 *
 * <p> A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog  
 *
 * API tests for ProductOfferingQualificationApi 
 */
public class ProductOfferingQualificationApiTest {


    private ProductOfferingQualificationApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://serverRoot/api/mef", ProductOfferingQualificationApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Create a ProductOfferingQualification
     *
     * A request initiated by the Buyer to determine whether the Seller can feasibly deliver a particular Product (or Products) to a specific set of geographic locations specified by a set of Site/Address filter criteria. The Seller also provides estimated time intervals to complete these deliveries. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productOfferingQualificationCreateTest() {
        ProductOfferingQualificationCreate productOfferingQualification = null;
        //ProductOfferingQualification response = api.productOfferingQualificationCreate(productOfferingQualification);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Retrieve a list of ProductOfferingQualifications based on a set of criteria
     *
     * The Buyer requests a list of POQs (in any state) from the Seller based on a set of POQ filter criteria.  For each POQ returned, the Seller also provides a POQ Identifier that uniquely identifies this POQ within the Seller. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productOfferingQualificationFindTest() {
        String state = null;
        String projectId = null;
        Date requestedResponseDateGt = null;
        Date requestedResponseDateLt = null;
        String offset = null;
        String limit = null;
        //List<ProductOfferingQualificationFind> response = api.productOfferingQualificationFind(state, projectId, requestedResponseDateGt, requestedResponseDateLt, offset, limit);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get a ProductOfferingQualification based on its id
     *
     * The Buyer requests the full details of a single Product Offering Qualification based on a POQ identifier. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productOfferingQualificationGetTest() {
        String productOfferingQualificationId = null;
        //ProductOfferingQualification response = api.productOfferingQualificationGet(productOfferingQualificationId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
