/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog  
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.api;

import java.util.Date;
import io.swagger.model.ErrorRepresentation;
import io.swagger.model.ProductOrder;
import io.swagger.model.ProductOrderCreate;
import io.swagger.model.ProductOrderSummary;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * MEF LSO Sonata
 *
 * <p> A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog  
 *
 * API tests for ProductOrderApi 
 */
public class ProductOrderApiTest {


    private ProductOrderApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://serverRoot/api/mef", ProductOrderApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Create a product order
     *
     * This operation is used to create an order. Depending on the order activity, one can \&quot;INSTALL\&quot;, \&quot;CHANGE\&quot;, or \&quot;DISCONNECT\&quot; an associated product.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productOrderCreateTest() {
        ProductOrderCreate productOrder = null;
        //ProductOrder response = api.productOrderCreate(productOrder);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Find a list of product order(s)
     *
     * This operation is used to retrieve one or more product orders based upon filter criteria specified on input.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productOrderFindTest() {
        String buyerId = null;
        String sellerId = null;
        String state = null;
        Date buyerRequestedDateGt = null;
        Date buyerRequestedDateLt = null;
        Date orderDateGt = null;
        Date orderDateLt = null;
        Date requestedStartDateGt = null;
        Date requestedStartDateLt = null;
        Date requestedCompletionDateGt = null;
        Date requestedCompletionDateLt = null;
        Date expectedCompletionDateGt = null;
        Date expectedCompletionDateLt = null;
        Date completionDateGt = null;
        Date completionDateLt = null;
        Date orderCancellationDateGt = null;
        Date orderCancellationDateLt = null;
        String siteName = null;
        String siteCompanyName = null;
        String siteCustomerName = null;
        String projectId = null;
        String externalId = null;
        String offset = null;
        String limit = null;
        //List<ProductOrderSummary> response = api.productOrderFind(buyerId, sellerId, state, buyerRequestedDateGt, buyerRequestedDateLt, orderDateGt, orderDateLt, requestedStartDateGt, requestedStartDateLt, requestedCompletionDateGt, requestedCompletionDateLt, expectedCompletionDateGt, expectedCompletionDateLt, completionDateGt, completionDateLt, orderCancellationDateGt, orderCancellationDateLt, siteName, siteCompanyName, siteCustomerName, projectId, externalId, offset, limit);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get a product order (by id)
     *
     * This operation is used to retrieve a single product order based upon a specified product order id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productOrderGetTest() {
        String productOrderId = null;
        //ProductOrder response = api.productOrderGet(productOrderId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
