package io.swagger.server.api.verticle;

import io.swagger.server.api.model.ErrorRepresentation;
import io.swagger.server.api.model.Event;
import io.swagger.server.api.model.EventPlus;
import io.swagger.server.api.MainApiException;

public final class NotificationApiException extends MainApiException {
    public NotificationApiException(int statusCode, String statusMessage) {
        super(statusCode, statusMessage);
    }
    
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_408_Exception = new NotificationApiException(408, "Request Time-out  List of supported error codes: - 63: Request time-out");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationProductOrderAttributeValueChangeNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_408_Exception = new NotificationApiException(408, "Request Time-out  List of supported error codes: - 63: Request time-out");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationProductOrderCreationNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_408_Exception = new NotificationApiException(408, "Request Time-out  List of supported error codes: - 63: Request time-out");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationProductOrderInformationRequiredNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_408_Exception = new NotificationApiException(408, "Request Time-out  List of supported error codes: - 63: Request time-out");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationProductOrderStateChangeNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationQuoteAttributeValueChangeNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationQuoteCreationNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationQuoteInformationRequiredNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_400_Exception = new NotificationApiException(400, "Bad Request  List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_401_Exception = new NotificationApiException(401, "Unauthorized  List of supported error codes: - 40: Missing credentials - 41: Invalid credentials - 42: Expired credentials");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_403_Exception = new NotificationApiException(403, "Forbidden  List of supported error codes: - 50: Access denied - 51: Forbidden requester - 52: Forbidden user - 53: Too many requests");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_404_Exception = new NotificationApiException(404, "Not Found  List of supported error codes: - 60: Resource not found");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_405_Exception = new NotificationApiException(405, "Method Not Allowed  List of supported error codes: - 61: Method not allowed");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_422_Exception = new NotificationApiException(422, "Unprocessable entity  Functional error");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_500_Exception = new NotificationApiException(500, "Internal Server Error  List of supported error codes: - 1: Internal error");
    public static final NotificationApiException Notification_notificationQuoteStateChangeNotification_503_Exception = new NotificationApiException(503, "Service Unavailable  ");
    

}