/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Agreement reference. An agreement represents a contract or arrangement, either written or verbal and sometimes enforceable by law, such as a service level agreement or a customer price agreement.
 * @param id Unique identifier of the agreement
 * @param name Name of the agreement
 * @param path A URI/URL to where the agreement resides.
 */
data class Agreement(
        /* Unique identifier of the agreement */
        val id: kotlin.String,
        /* Name of the agreement */
        val name: kotlin.String? = null,
        /* A URI/URL to where the agreement resides. */
        val path: kotlin.String? = null
) {

}

