/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * If in the request the buyer has requested to have alternate product proposals, then this class represents these proposals.
 * @param @type Technical attribute to extend the class.
 * @param eligibleProductOffering
 * @param id Identifier of the Product Offering Qualification alternate proposal
 * @param installationInterval
 * @param productSpecification
 */
data class AlternateProductProposal(
        /* Identifier of the Product Offering Qualification alternate proposal */
        val id: kotlin.String,
        /* Technical attribute to extend the class. */
        val type: kotlin.String? = null,
        val eligibleProductOffering: kotlin.Array<ProductOfferingRef>? = null,
        val installationInterval: TimeInterval? = null,
        val productSpecification: ProductSpecificationRef? = null
) {

}

