/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Structure to allow Seller to answer to a cancel order request
 * @param @schemaLocation Technical attribute to extend this class.
 * @param @type Technical attribute to extend this class.
 * @param cancellationDeniedReason If seller denied cancellation request he could here provide reason for this denial
 * @param cancellationReason An optional free-form text field for the Seller to provide additional information regarding the reason for the cancellation.
 * @param href Hyperlink to access order cancellation request.This is not a product order href.
 * @param id Unique identifier for the order cancellation request that is generated by the Seller when the order cancellation is accepted via an API. This is not the order id.
 * @param productOrder
 * @param requestedCancellationDate Identifies the date the Seller cancelled the Order.
 * @param state
 */
data class CancelProductOrder(
        /* Unique identifier for the order cancellation request that is generated by the Seller when the order cancellation is accepted via an API. This is not the order id. */
        val id: kotlin.String,
        val productOrder: ProductOrderRefCancel,
        /* Identifies the date the Seller cancelled the Order. */
        val requestedCancellationDate: java.time.LocalDateTime,
        val state: TaskStateType,
        /* Technical attribute to extend this class. */
        val schemaLocation: kotlin.String? = null,
        /* Technical attribute to extend this class. */
        val type: kotlin.String? = null,
        /* If seller denied cancellation request he could here provide reason for this denial */
        val cancellationDeniedReason: kotlin.String? = null,
        /* An optional free-form text field for the Seller to provide additional information regarding the reason for the cancellation. */
        val cancellationReason: kotlin.String? = null,
        /* Hyperlink to access order cancellation request.This is not a product order href. */
        val href: kotlin.String? = null
) {

}

