/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Structure to response for a quote cancellation/rejection request
 * @param externalId External Id of the quote (buyer quote id). If provided by seller this information is send back in the response.
 * @param id id of the quote to be cancelled
 * @param quoteEffectiveStateChangeDate Cancellation or rejection date (effective)
 * @param state
 */
data class ChangeQuoteStateResponse(
        /* id of the quote to be cancelled */
        val id: kotlin.String,
        /* Cancellation or rejection date (effective) */
        val quoteEffectiveStateChangeDate: java.time.LocalDateTime,
        val state: QuoteStateType,
        /* External Id of the quote (buyer quote id). If provided by seller this information is send back in the response. */
        val externalId: kotlin.String? = null
) {

}

