/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Contact allow to capture contact information. It is used to capture billing account contact information
 * @param @referredType Technical attribut to extend API
 * @param contactName Identifies the name of the person or office to be contacted on billing matters.
 * @param emailAdress Identifies the electronic mail address of the Billing Contact when a Buyer profile does not already exist.
 * @param phoneNumber Identifies the telephone number (excluding extension) of the billing contact
 * @param phoneNumberExtension Identifies the telephone number extension of the billing contact
 * @param streetAdress Identifies the address of the person or office to be contacted on billing matters.
 */
data class Contact(
        /* Identifies the name of the person or office to be contacted on billing matters. */
        val contactName: kotlin.String,
        /* Identifies the electronic mail address of the Billing Contact when a Buyer profile does not already exist. */
        val emailAdress: kotlin.String,
        /* Identifies the telephone number (excluding extension) of the billing contact */
        val phoneNumber: kotlin.String,
        /* Identifies the address of the person or office to be contacted on billing matters. */
        val streetAdress: kotlin.String,
        /* Technical attribut to extend API */
        val referredType: kotlin.String? = null,
        /* Identifies the telephone number extension of the billing contact */
        val phoneNumberExtension: kotlin.String? = null
) {

}

