/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * To describe a duration (period of time) with a value and an unit (day, month, etc...)
 * @param unit
 * @param value value of the duration
 */
data class Duration(
        val unit: DurationUnit,
        /* value of the duration */
        val value: kotlin.Int
) {

}

