/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Class used to describe API response error
 * @param @schemaLocation it provides a link to the schema describing a REST resource.
 * @param @type The class type of a REST resource.
 * @param code Application related code (as defined in the API or from a common list)
 * @param message Text that provide more details and corrective actions related to the error. This can be shown to a client user.
 * @param reason Text that explains the reason for error. This can be shown to a client user.
 * @param referenceError url pointing to documentation describing the error
 * @param status http error code extension like 400-2
 */
data class ErrorRepresentation(
        /* Application related code (as defined in the API or from a common list) */
        val code: kotlin.Int,
        /* Text that explains the reason for error. This can be shown to a client user. */
        val reason: kotlin.String,
        /* it provides a link to the schema describing a REST resource. */
        val schemaLocation: kotlin.String? = null,
        /* The class type of a REST resource. */
        val type: kotlin.String? = null,
        /* Text that provide more details and corrective actions related to the error. This can be shown to a client user. */
        val message: kotlin.String? = null,
        /* url pointing to documentation describing the error */
        val referenceError: kotlin.String? = null,
        /* http error code extension like 400-2 */
        val status: kotlin.String? = null
) {

}

