/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Event class is used to describe information structure used for notification.
 * @param event
 * @param eventId
 * @param eventTime
 * @param eventType
 */
data class Event(
        val event: ProductOrderEvent,
        val eventId: kotlin.String,
        val eventTime: java.time.LocalDateTime,
        val eventType: ProductOrderEventType
) {

}

