/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A type of Address that has a discrete field and value for each type of boundary or identifier down to the lowest level of detail. For example “street number” is one field, “street name” is another field, etc. This structure is used in the request addressValidation only
 * @param city City that the address is in
 * @param country Country that the address is in
 * @param geographicSubAddress
 * @param locality \"An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi-rural in nature.\" [ANZLIC-STREET], or a suburb \"a bounded locality within a city, town or shire principally of urban character \" [ANZLICSTREET].
 * @param postCodeExtension The four-digit extension on an American postal code, what comes after the hyphen when specified.
 * @param postcode Descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also known as zipcode)
 * @param stateOrProvince The State or Province that the address is in
 * @param streetName Name of the street or other street type
 * @param streetNr Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses
 * @param streetNrLast Last number in a range of street numbers allocated to a property
 * @param streetNrLastSuffix Last street number suffix for a ranged address
 * @param streetNrSuffix The first street number suffix
 * @param streetSuffix A modifier denoting a relative direction
 * @param streetType Alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf
 */
data class FieldedAddressRequest(
        /* City that the address is in */
        val city: kotlin.String? = null,
        /* Country that the address is in */
        val country: kotlin.String? = null,
        val geographicSubAddress: GeographicSubAddressRequest? = null,
        /* \"An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi-rural in nature.\" [ANZLIC-STREET], or a suburb \"a bounded locality within a city, town or shire principally of urban character \" [ANZLICSTREET]. */
        val locality: kotlin.String? = null,
        /* The four-digit extension on an American postal code, what comes after the hyphen when specified. */
        val postCodeExtension: kotlin.String? = null,
        /* Descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also known as zipcode) */
        val postcode: kotlin.String? = null,
        /* The State or Province that the address is in */
        val stateOrProvince: kotlin.String? = null,
        /* Name of the street or other street type */
        val streetName: kotlin.String? = null,
        /* Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses */
        val streetNr: kotlin.String? = null,
        /* Last number in a range of street numbers allocated to a property */
        val streetNrLast: kotlin.String? = null,
        /* Last street number suffix for a ranged address */
        val streetNrLastSuffix: kotlin.String? = null,
        /* The first street number suffix */
        val streetNrSuffix: kotlin.String? = null,
        /* A modifier denoting a relative direction */
        val streetSuffix: kotlin.String? = null,
        /* Alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf */
        val streetType: kotlin.String? = null
) {

}

