/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * A type of Address that has discrete fields for each type of boundary or identifier with the exception of street and more specific location details, which are combined into a maximum of two strings based on local postal addressing conventions
 * @param addrLine1 The first address line in a formatted address
 * @param addrLine2 The second address line in a formatted address
 * @param city City that the address is in
 * @param country Country that the address is in
 * @param locality \"An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi-rural in nature.\" [ANZLIC-STREET], or a suburb \"a bounded locality within a city, town or shire principally of urban character \" [ANZLICSTREET].
 * @param postCodeExtension The four-digit extension on an American postal code, what comes after the hyphen when specified.
 * @param postcode Descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also known as zipcode)
 * @param stateOrProvince The State or Province that the address is in
 */
data class FormattedAddressRequest(
        /* The first address line in a formatted address */
        val addrLine1: kotlin.String,
        /* The second address line in a formatted address */
        val addrLine2: kotlin.String? = null,
        /* City that the address is in */
        val city: kotlin.String? = null,
        /* Country that the address is in */
        val country: kotlin.String? = null,
        /* \"An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi-rural in nature.\" [ANZLIC-STREET], or a suburb \"a bounded locality within a city, town or shire principally of urban character \" [ANZLICSTREET]. */
        val locality: kotlin.String? = null,
        /* The four-digit extension on an American postal code, what comes after the hyphen when specified. */
        val postCodeExtension: kotlin.String? = null,
        /* Descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also known as zipcode) */
        val postcode: kotlin.String? = null,
        /* The State or Province that the address is in */
        val stateOrProvince: kotlin.String? = null
) {

}

