/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A set of coordinates (typically including latitude and longitude) that describes a particular location on earth.
 * @param geographicPoint
 * @param id Unique Identifier of a GeographicLocation
 * @param spatialRef The spatial reference system used to determine the coordinates
 */
data class GeographicLocation(
        val geographicPoint: kotlin.Array<GeographicPoint>,
        /* The spatial reference system used to determine the coordinates */
        val spatialRef: kotlin.String,
        /* Unique Identifier of a GeographicLocation */
        val id: kotlin.String? = null
) {

}

