/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Technical structure to provide site list retrieve in the GET operation
 * @param geographicAddress
 * @param id id of the site. This is coud be used in other API as a place
 * @param siteCompanyName The name of the company that is the administrative authority (e.g. controls access) for this Service Site. (For example, the building owner)
 * @param siteContactName Name of the relatedParty which has role 'Site Contact' in the Site record.
 * @param siteCustomerName The name of the company that is the administrative authority for the space within this Service Site. (For example, the company leasing space in a multi-tenant building).
 * @param siteDescription A textual description of the Service Site.
 * @param siteName A name commonly used by people to refer to this Service Site.
 * @param siteType This defines whether a Service Site is public or private.
 * @param status
 */
data class GeographicSiteFindResp(
        val geographicAddress: GeographicAddressFindResp? = null,
        /* id of the site. This is coud be used in other API as a place */
        val id: kotlin.String? = null,
        /* The name of the company that is the administrative authority (e.g. controls access) for this Service Site. (For example, the building owner) */
        val siteCompanyName: kotlin.String? = null,
        /* Name of the relatedParty which has role 'Site Contact' in the Site record. */
        val siteContactName: kotlin.String? = null,
        /* The name of the company that is the administrative authority for the space within this Service Site. (For example, the company leasing space in a multi-tenant building). */
        val siteCustomerName: kotlin.String? = null,
        /* A textual description of the Service Site. */
        val siteDescription: kotlin.String? = null,
        /* A name commonly used by people to refer to this Service Site. */
        val siteName: kotlin.String? = null,
        /* This defines whether a Service Site is public or private. */
        val siteType: kotlin.String? = null,
        val status: Status? = null
) {

}

