/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Resource used to support a request for a validation address : check if a geographic address described by values attributes exists) If exist, id is provided if not, alternate address(es) could be provided
 * @param id Unique identifier of the Address Validation (Not an address id !!)
 * @param requestedAddress
 * @param validationDate Date when the address validation is performed
 * @param validationResult
 * @param verifiedAddress
 */
data class GeographicAddressValidation(
        val requestedAddress: GeographicAddressRequestBuyerInput,
        /* Unique identifier of the Address Validation (Not an address id !!) */
        val id: kotlin.String? = null,
        /* Date when the address validation is performed */
        val validationDate: java.time.LocalDateTime? = null,
        val validationResult: ValidationResult? = null,
        val verifiedAddress: kotlin.Array<GeographicAddressSellerResponse>? = null
) {

}

