/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * A geometric point on earth, which can include a latitude, longitude, and elevation in “decimal degrees” format.
 * @param id A unique identifier for the geographic point.
 * @param latitude The latitude expressed in decimal degrees format
 * @param longitude The longitude expressed in decimal degrees format
 */
data class GeographicPoint(
        /* The latitude expressed in decimal degrees format */
        val latitude: kotlin.String,
        /* The longitude expressed in decimal degrees format */
        val longitude: kotlin.String,
        /* A unique identifier for the geographic point. */
        val id: kotlin.String? = null
) {

}

