/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * This resource is used to manage notification subscription.
 * @param callback This callback address is an url. the norification will be sent to this url address
 * @param id id of the Hub
 * @param query This attribute is used to define notification type. Example: \",\"query\":”eventType = ProductOfferingQualificationStateChangeNotification”}
 */
data class Hub(
        /* This callback address is an url. the norification will be sent to this url address */
        val callback: kotlin.String,
        /* id of the Hub */
        val id: kotlin.String,
        /* This attribute is used to define notification type. Example: \",\"query\":”eventType = ProductOfferingQualificationStateChangeNotification”} */
        val query: kotlin.String
) {

}

