/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * This class is used to request a HUB creation - Used in the POST operation.
 * @param callback This attribute is the callback url where event will be sent when occurs, for instance an url http://yourdomain/listener/api/v1/event
 * @param query This attribute is used to define notification type. Example: \",\"query\":”eventType = ProductOfferingQualificationStateChangeNotification”}
 */
data class HubInput(
        /* This attribute is the callback url where event will be sent when occurs, for instance an url http://yourdomain/listener/api/v1/event */
        val callback: kotlin.String,
        /* This attribute is used to define notification type. Example: \",\"query\":”eventType = ProductOfferingQualificationStateChangeNotification”} */
        val query: kotlin.String
) {

}

