/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * base / value business entity used to represent money
 * @param unit Currency (ISO4217 norm uses 3 letters to define the currency
 * @param value A positive floating point number
 */
data class Money(
        /* Currency (ISO4217 norm uses 3 letters to define the currency */
        val unit: kotlin.String,
        /* A positive floating point number */
        val value: kotlin.Float
) {

}

