/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * An optional array of messages associated with the Order
 * @param code The code associated with the Message
 * @param correctionRequired Indicates whether the Buyer must submit an updated Order to resolve the Error/Jeopardy condition.
 * @param field The field/attribute on the Order associated with message
 * @param messageInformation A description of the error condition or information to be conveyed to the Buyer
 * @param severity
 */
data class OrderMessage(
        /* A description of the error condition or information to be conveyed to the Buyer */
        val messageInformation: kotlin.String,
        val severity: Severity,
        /* The code associated with the Message */
        val code: kotlin.String? = null,
        /* Indicates whether the Buyer must submit an updated Order to resolve the Error/Jeopardy condition. */
        val correctionRequired: kotlin.Boolean? = null,
        /* The field/attribute on the Order associated with message */
        val field: kotlin.String? = null
) {

}

