/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * This class allows the ability to associate one order item to another order item.
 * @param id The id of the targeted order item by the relationship
 * @param productOrderId Id of another product order if this relationship is between two distinct orders.
 * @param type Indicates the type of order item relationship
 */
data class OrderItemRelationShip(
        /* The id of the targeted order item by the relationship */
        val id: kotlin.String,
        /* Indicates the type of order item relationship */
        val type: kotlin.String,
        /* Id of another product order if this relationship is between two distinct orders. */
        val productOrderId: kotlin.String? = null
) {

}

