/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Is an amount, usually of money, that modifies the price charged for an order item
 * @param @schemaLocation Link to the schema describing this REST resource
 * @param @type Indicates the (class) type of the price alteration
 * @param applicationDuration Duration during which the alteration applies on the order item price (for instance 2 months free of charge for the recurring charge).
 * @param description A narrative that explains in detail the semantics of this order item price alteration.
 * @param name A short descriptive name such as \"Monthly discount\".
 * @param percentage
 * @param price
 * @param priceType A category that describes the price such as recurring, one time and usage.
 * @param priority Priority level for applying this alteration among all the defined alterations on the order item price
 * @param recurringChargePeriod Could be month, week...
 * @param unitOfMeasure Could be minutes, GB...
 */
data class PriceAlteration(
        /* A category that describes the price such as recurring, one time and usage. */
        val priceType: kotlin.String,
        /* Link to the schema describing this REST resource */
        val schemaLocation: kotlin.String? = null,
        /* Indicates the (class) type of the price alteration */
        val type: kotlin.String? = null,
        /* Duration during which the alteration applies on the order item price (for instance 2 months free of charge for the recurring charge). */
        val applicationDuration: kotlin.Int? = null,
        /* A narrative that explains in detail the semantics of this order item price alteration. */
        val description: kotlin.String? = null,
        /* A short descriptive name such as \"Monthly discount\". */
        val name: kotlin.String? = null,
        val percentage: kotlin.Float? = null,
        val price: Price? = null,
        /* Priority level for applying this alteration among all the defined alterations on the order item price */
        val priority: kotlin.Int? = null,
        /* Could be month, week... */
        val recurringChargePeriod: kotlin.String? = null,
        /* Could be minutes, GB... */
        val unitOfMeasure: kotlin.String? = null
) {

}

