/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Product reference used to describe product relationship.
 * @param buyerProductId Targeted Buyer product id - Informative
 * @param href Reference of the product
 * @param id Unique identifier of the product
 */
data class ProductRef(
        /* Unique identifier of the product */
        val id: kotlin.String,
        /* Targeted Buyer product id - Informative */
        val buyerProductId: kotlin.String? = null,
        /* Reference of the product */
        val href: kotlin.String? = null
) {

}

