/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * A reference to a productOrder and optionally to an order item.
 * @param href Hyperlink to the productOrder
 * @param id Identifier of the productOrder(provided by the seller)
 * @param orderItemId Identifier of the line item (generally it is a sequence number 01, 02, 03, ...)
 */
data class ProductOrderRef(
        /* Identifier of the productOrder(provided by the seller) */
        val id: kotlin.String,
        /* Identifier of the line item (generally it is a sequence number 01, 02, 03, ...) */
        val orderItemId: kotlin.String,
        /* Hyperlink to the productOrder */
        val href: kotlin.String? = null
) {

}

