/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * An enumeration of valid order states
 * Values: acknowledged,rejected,inProgress,pending,held,assessingCancellation,pendingCancellation,cancelled,inProgressPeriodconfigured,inProgressPeriodconfirmed,inProgressPeriodjeopardy,failed,partial,completed
 */
enum class ProductOrderStateType(val value: kotlin.String) {

    acknowledged("acknowledged"),

    rejected("rejected"),

    inProgress("inProgress"),

    pending("pending"),

    held("held"),

    assessingCancellation("assessingCancellation"),

    pendingCancellation("pendingCancellation"),

    cancelled("cancelled"),

    inProgressPeriodconfigured("inProgress.configured"),

    inProgressPeriodconfirmed("inProgress.confirmed"),

    inProgressPeriodjeopardy("inProgress.jeopardy"),

    failed("failed"),

    partial("partial"),

    completed("completed");

}

