/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * This class is used to describe attribute to be used for requesting POQ list (used in the GET by list)
 * @param id The Serviceability Request's unique identifier.
 * @param projectId This value MAY be assigned by the Buyer/Seller to identify a project the serviceability request is associated with.
 * @param requestedResponseDate Corresponds to desiredResponseDate - The date a response for the service request is desired.
 * @param state
 */
data class ProductOfferingQualificationFind(
        /* The Serviceability Request's unique identifier. */
        val id: kotlin.String? = null,
        /* This value MAY be assigned by the Buyer/Seller to identify a project the serviceability request is associated with. */
        val projectId: kotlin.String? = null,
        /* Corresponds to desiredResponseDate - The date a response for the service request is desired. */
        val requestedResponseDate: java.time.LocalDateTime? = null,
        val state: ProductOfferingQualificationStateType? = null
) {

}

