/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Indicate a commitment term associated to the product
 * @param description Description of the commitment
 * @param duration
 * @param name Name of the commitment
 * @param validFor
 */
data class ProductTerm(
        /* Description of the commitment */
        val description: kotlin.String? = null,
        val duration: Quantity? = null,
        /* Name of the commitment */
        val name: kotlin.String? = null,
        val validFor: TimePeriod? = null
) {

}

