/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A product has relationships to other products.
 * @param product
 * @param type Indicates whether the type of relationship is \"bundled\", \"reliesOn\", or \"comesFrom\"
 */
data class ProductRelationship(
        val product: ProductRef,
        /* Indicates whether the type of relationship is \"bundled\", \"reliesOn\", or \"comesFrom\" */
        val type: kotlin.String
) {

}

