/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A grouping of POQ Items formulated into a request made by a Buyer to a Seller
 * @param @schemaLocation Technical attribute to extend the class
 * @param @type When sub-classing, this defines the sub-class entity name
 * @param effectiveQualificationCompletionDate Effective date seller provides qualification result.
 * @param expectedResponseDate The date the seller is expected to provide qualification result.
 * @param href Link to this POQ resource
 * @param id The Serviceability Request's unique identifier.
 * @param instantSyncQualification If this flag is set to Yes, Buyer requests to have instant qualificationto be provided in operation POST response
 * @param productOfferingQualificationItem
 * @param projectId This value MAY be assigned by the Buyer/Seller to identify a project the serviceability request is associated with.
 * @param provideAlternative This Boolean allows requester (buyer) to indicate if he is willing to get alternate proposal if requested product not available.
 * @param relatedParty
 * @param requestedResponseDate Corresponds to desiredResponseDate - The date a response for the service request is desired.
 * @param state
 * @param stateChange
 */
data class ProductOfferingQualification(
        /* The Serviceability Request's unique identifier. */
        val id: kotlin.String,
        val productOfferingQualificationItem: kotlin.Array<ProductOfferingQualificationItem>,
        val relatedParty: kotlin.Array<RelatedParty>,
        val state: ProductOfferingQualificationStateType,
        /* Technical attribute to extend the class */
        val schemaLocation: kotlin.String? = null,
        /* When sub-classing, this defines the sub-class entity name */
        val type: kotlin.String? = null,
        /* Effective date seller provides qualification result. */
        val effectiveQualificationCompletionDate: java.time.LocalDateTime? = null,
        /* The date the seller is expected to provide qualification result. */
        val expectedResponseDate: java.time.LocalDateTime? = null,
        /* Link to this POQ resource */
        val href: kotlin.String? = null,
        /* If this flag is set to Yes, Buyer requests to have instant qualificationto be provided in operation POST response */
        val instantSyncQualification: kotlin.Boolean? = null,
        /* This value MAY be assigned by the Buyer/Seller to identify a project the serviceability request is associated with. */
        val projectId: kotlin.String? = null,
        /* This Boolean allows requester (buyer) to indicate if he is willing to get alternate proposal if requested product not available. */
        val provideAlternative: kotlin.Boolean? = null,
        /* Corresponds to desiredResponseDate - The date a response for the service request is desired. */
        val requestedResponseDate: java.time.LocalDateTime? = null,
        val stateChange: kotlin.Array<StateChange>? = null
) {

}

