/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A CreateProductOrder object is provided as input to the product order create operation.
 * @param @baseType Technical attribute to extend API
 * @param @schemaLocation Technical attribute to extend API
 * @param @type Technical attribute to extend API
 * @param billingAccount
 * @param buyerRequestDate Date when the order was submitted by the Buyer to the Seller
 * @param desiredResponse
 * @param expeditePriority Indicates that expedited treatment is requested and any charges generated in provisioning this request (e.g., additional engineering charges or labor charges if applicable) will be accepted by the buyer.
 * @param externalId Buyer Purchase Order Number: A number that uniquely identifies an order within the Buyer's enterprise
 * @param note
 * @param orderActivity
 * @param orderItem
 * @param orderVersion Buyer Order Version: The version number that the Buyer uses to refer to this particular version of the order.
 * @param pricingMethod
 * @param pricingReference The identifier references the previously agreed upon pricing terms, as applicable, based on the pricingMethod (e.g. a contract id or tariff id.
 * @param pricingTerm The length of the contract in months
 * @param priority An integer that specifies that expedited treatment is to be provided in a specific priority.
 * @param projectId An identifier that is used to group Orders that is important to the Buyer. A ProjectId can be used to relate multiple Orders together.
 * @param relatedBuyerPON Related Buyer Purchase Order Number (RPON) - Identifies the Buyer Purchase Order Number that is related to this order.
 * @param relatedParty
 * @param requestedCompletionDate Identifies the Buyer's desired due date (requested delivery date)
 * @param requestedStartDate If specified, identifies the Buyer's desired date for order processing to start
 * @param tspRestorationPriority Within the United States, indicates the provisioning and restoration priority as defined under the TSP Service Vendor Handbook.
 */
data class ProductOrderCreate(
        /* Date when the order was submitted by the Buyer to the Seller */
        val buyerRequestDate: java.time.LocalDateTime,
        val desiredResponse: DesiredOrderResponses,
        /* Buyer Purchase Order Number: A number that uniquely identifies an order within the Buyer's enterprise */
        val externalId: kotlin.String,
        val orderActivity: OrderActivity,
        val orderItem: kotlin.Array<ProductOrderItemCreate>,
        /* Buyer Order Version: The version number that the Buyer uses to refer to this particular version of the order. */
        val orderVersion: kotlin.String,
        val relatedParty: kotlin.Array<RelatedParty>,
        /* Identifies the Buyer's desired due date (requested delivery date) */
        val requestedCompletionDate: java.time.LocalDateTime,
        /* Technical attribute to extend API */
        val baseType: kotlin.String? = null,
        /* Technical attribute to extend API */
        val schemaLocation: kotlin.String? = null,
        /* Technical attribute to extend API */
        val type: kotlin.String? = null,
        val billingAccount: BillingAccountRef? = null,
        /* Indicates that expedited treatment is requested and any charges generated in provisioning this request (e.g., additional engineering charges or labor charges if applicable) will be accepted by the buyer. */
        val expeditePriority: kotlin.Boolean? = null,
        val note: kotlin.Array<Note>? = null,
        val pricingMethod: PricingMethod? = null,
        /* The identifier references the previously agreed upon pricing terms, as applicable, based on the pricingMethod (e.g. a contract id or tariff id. */
        val pricingReference: kotlin.String? = null,
        /* The length of the contract in months */
        val pricingTerm: kotlin.Int? = null,
        /* An integer that specifies that expedited treatment is to be provided in a specific priority. */
        val priority: kotlin.Int? = null,
        /* An identifier that is used to group Orders that is important to the Buyer. A ProjectId can be used to relate multiple Orders together. */
        val projectId: kotlin.String? = null,
        /* Related Buyer Purchase Order Number (RPON) - Identifies the Buyer Purchase Order Number that is related to this order. */
        val relatedBuyerPON: kotlin.String? = null,
        /* If specified, identifies the Buyer's desired date for order processing to start */
        val requestedStartDate: java.time.LocalDateTime? = null,
        /* Within the United States, indicates the provisioning and restoration priority as defined under the TSP Service Vendor Handbook. */
        val tspRestorationPriority: kotlin.String? = null
) {

}

