/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Structure to define GET without id response. A list of productOrder matching request criteria. Provides Product order summary view.
 * @param externalId ID given by the consumer and only understandable by him (to facilitate his searches afterwards). MEF: Buyer Purchase Order Number
 * @param id ID created on repository side (OM system) MEF: Unique identifier for the order that is generated by the Seller when the order is initially accepted via an API.
 * @param orderDate Date when the order was created
 * @param state
 */
data class ProductOrderSummary(
        /* ID given by the consumer and only understandable by him (to facilitate his searches afterwards). MEF: Buyer Purchase Order Number */
        val externalId: kotlin.String,
        /* ID created on repository side (OM system) MEF: Unique identifier for the order that is generated by the Seller when the order is initially accepted via an API. */
        val id: kotlin.String,
        /* Date when the order was created */
        val orderDate: java.time.LocalDateTime,
        val state: ProductOrderStateType
) {

}

