/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A reference to a product order used to perform cancellation request.
 * @param @referredType Technical attribute to extend the API
 * @param externalId A number that uniquely identifies an order within the buyer's enterprise. Must be provided if provided when the order was initially accepted
 * @param href Hyperlink to access the order
 * @param id Unique (within the ordering domain) identifier for the order that is generated by the seller when the order is initially accepted.
 * @param state
 * @param version The version number that the Buyer uses to refer to this particular version of the order. This not checked for conformance (informative information)
 */
data class ProductOrderRefCancel(
        /* Unique (within the ordering domain) identifier for the order that is generated by the seller when the order is initially accepted. */
        val id: kotlin.String,
        /* Technical attribute to extend the API */
        val referredType: kotlin.String? = null,
        /* A number that uniquely identifies an order within the buyer's enterprise. Must be provided if provided when the order was initially accepted */
        val externalId: kotlin.String? = null,
        /* Hyperlink to access the order */
        val href: kotlin.String? = null,
        val state: ProductOrderStateType? = null,
        /* The version number that the Buyer uses to refer to this particular version of the order. This not checked for conformance (informative information) */
        val version: kotlin.String? = null
) {

}

