/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * This structure serves as a request for a product offering qualification item An individual article included in a POQ that describes a Product of a particular type (Product Offering) being delivered to a specific geographical location.  The objective is to determine if it is feasible for the Seller to deliver this item as described and for the Seller to inform the Buyer of the estimated time interval to complete this delivery.
 * @param @type When sub-classing, this defines the sub-class entity name
 * @param action
 * @param id Id of the productOfferingQualification item. This id must be unique within POQ create request
 * @param product
 * @param productOffering
 * @param productOfferingQualificationItemRelationship
 * @param relatedParty
 */
data class ProductOfferingQualificationItemCreate(
        /* Id of the productOfferingQualification item. This id must be unique within POQ create request */
        val id: kotlin.String,
        val product: Product,
        /* When sub-classing, this defines the sub-class entity name */
        val type: kotlin.String? = null,
        val action: ProductActionType? = null,
        val productOffering: ProductOfferingRef? = null,
        val productOfferingQualificationItemRelationship: kotlin.Array<ProductOfferingQualificationItemRelationship>? = null,
        val relatedParty: kotlin.Array<RelatedParty>? = null
) {

}

