/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Product structure used for notification
 * @param buyerProductId Buyer product Id - informative information
 * @param id Unique (within the product domain) identifier for the product that is generated by the seller when the product is instantiated.
 * @param productSpecification
 * @param relatedParty
 */
data class ProductEvent(
        /* Buyer product Id - informative information */
        val buyerProductId: kotlin.String? = null,
        /* Unique (within the product domain) identifier for the product that is generated by the seller when the product is instantiated. */
        val id: kotlin.String? = null,
        val productSpecification: ProductSpecification? = null,
        val relatedParty: kotlin.Array<RelatedParty>? = null
) {

}

