/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Class used to provide product overview retrieved in GET (by list) operation
 * @param buyerProductId This identifier is optionally provided during the product ordering and stored for informative purpose in the seller inventory
 * @param href Reference of the product
 * @param id Unique identifier of the product
 * @param productOffering
 * @param productSpecification
 * @param startDate The date from which the product starts
 * @param status
 */
data class ProductSummary(
        /* Unique identifier of the product */
        val id: kotlin.String,
        val status: ProductStatus,
        /* This identifier is optionally provided during the product ordering and stored for informative purpose in the seller inventory */
        val buyerProductId: kotlin.String? = null,
        /* Reference of the product */
        val href: kotlin.String? = null,
        val productOffering: ProductOfferingRef? = null,
        val productSpecification: ProductSpecificationSummary? = null,
        /* The date from which the product starts */
        val startDate: java.time.LocalDateTime? = null
) {

}

