/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Using to refer a serviceability request previously done
 * @param @referredType Technical attribute to extend the API
 * @param href Hyperlink to the qualification previously done for this item
 * @param id id of the qualification previously done for this item
 * @param qualificationItem item id of the qualification previously done for this item
 */
data class QualificationRef(
        /* Technical attribute to extend the API */
        val referredType: kotlin.String? = null,
        /* Hyperlink to the qualification previously done for this item */
        val href: kotlin.String? = null,
        /* id of the qualification previously done for this item */
        val id: kotlin.String? = null,
        /* item id of the qualification previously done for this item */
        val qualificationItem: kotlin.String? = null
) {

}

