/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * A quote which can be used to negotiate service and product acquisition or modification between a customer and a service provider
 * @param @baseType Indicates the base (class) type of the quote.
 * @param @schemaLocation Link to the schema describing the REST resource.
 * @param @type Indicates the (class) type of the quote.
 * @param agreement
 * @param description Description of the quote
 * @param effectiveQuoteCompletionDate Date when the quoted was Cancelled or Rejected or Accepted
 * @param expectedFulfillmentStartDate This is the date wished by the requester to have the requested quote item(s) delivered
 * @param expectedQuoteCompletionDate This is the date filled by the seller to indicate expected quote completion date.
 * @param externalId ID given by the consumer and only understandable by him (to facilitate his searches afterwards)
 * @param href Hyperlink to access the quote
 * @param id Unique (within the quoting domain) identifier for the quote, as attributed by the quoting system
 * @param instantSyncQuoting If this flag is set to Yes, Buyer requests to have instant quoting to be provided in operation POST response
 * @param note
 * @param projectId This value MAY be assigned by the Buyer/Seller to identify a project the quoting request is associated with.
 * @param quoteDate Date when the quote was created
 * @param quoteItem
 * @param quoteLevel
 * @param relatedParty
 * @param requestedQuoteCompletionDate This is the date wished by the requester to have the quote completed (meaning priced)
 * @param state
 * @param validFor
 */
data class Quote(
        /* If this flag is set to Yes, Buyer requests to have instant quoting to be provided in operation POST response */
        val instantSyncQuoting: kotlin.Boolean,
        val quoteItem: kotlin.Array<QuoteItem>,
        val quoteLevel: QuoteLevel,
        val relatedParty: kotlin.Array<RelatedParty>,
        /* This is the date wished by the requester to have the quote completed (meaning priced) */
        val requestedQuoteCompletionDate: java.time.LocalDateTime,
        val state: QuoteStateType,
        /* Indicates the base (class) type of the quote. */
        val baseType: kotlin.String? = null,
        /* Link to the schema describing the REST resource. */
        val schemaLocation: kotlin.String? = null,
        /* Indicates the (class) type of the quote. */
        val type: kotlin.String? = null,
        val agreement: kotlin.Array<AgreementRef>? = null,
        /* Description of the quote */
        val description: kotlin.String? = null,
        /* Date when the quoted was Cancelled or Rejected or Accepted */
        val effectiveQuoteCompletionDate: java.time.LocalDateTime? = null,
        /* This is the date wished by the requester to have the requested quote item(s) delivered */
        val expectedFulfillmentStartDate: java.time.LocalDateTime? = null,
        /* This is the date filled by the seller to indicate expected quote completion date. */
        val expectedQuoteCompletionDate: java.time.LocalDateTime? = null,
        /* ID given by the consumer and only understandable by him (to facilitate his searches afterwards) */
        val externalId: kotlin.String? = null,
        /* Hyperlink to access the quote */
        val href: kotlin.String? = null,
        /* Unique (within the quoting domain) identifier for the quote, as attributed by the quoting system */
        val id: kotlin.String? = null,
        val note: kotlin.Array<Note>? = null,
        /* This value MAY be assigned by the Buyer/Seller to identify a project the quoting request is associated with. */
        val projectId: kotlin.String? = null,
        /* Date when the quote was created */
        val quoteDate: java.time.LocalDateTime? = null,
        val validFor: TimePeriod? = null
) {

}

