/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * This structure is used only in the POST operation for the request.
 * @param @baseType Indicates the base (class) type of the quote.
 * @param @schemaLocation Link to the schema describing the REST resource. Technical attribute to extend this class.
 * @param @type Indicates the (class) type of the quote. Technical attribute to extend this class.
 * @param agreement
 * @param description Description of the quote
 * @param expectedFulfillmentStartDate This is the date wished by the requester to have the requested quote item(s) delivered
 * @param externalId ID given by the consumer and only understandable by him (to facilitate his searches afterwards)
 * @param instantSyncQuoting If this flag is set to Yes, Buyer requests to have instant quoting to be provided in operation POST response
 * @param note
 * @param projectId This value MAY be assigned by the Buyer/Seller to identify a project the quoting request is associated with.
 * @param quoteItem
 * @param quoteLevel
 * @param relatedParty
 * @param requestedQuoteCompletionDate This is the date wished by the requester to have the quote completed (meaning priced). This attribute is not considered when instantSyncQuoting is set to Yes.
 */
data class QuoteCreate(
        val quoteItem: kotlin.Array<QuoteItemCreate>,
        val relatedParty: kotlin.Array<RelatedParty>,
        /* This is the date wished by the requester to have the quote completed (meaning priced). This attribute is not considered when instantSyncQuoting is set to Yes. */
        val requestedQuoteCompletionDate: java.time.LocalDateTime,
        /* Indicates the base (class) type of the quote. */
        val baseType: kotlin.String? = null,
        /* Link to the schema describing the REST resource. Technical attribute to extend this class. */
        val schemaLocation: kotlin.String? = null,
        /* Indicates the (class) type of the quote. Technical attribute to extend this class. */
        val type: kotlin.String? = null,
        val agreement: kotlin.Array<AgreementRef>? = null,
        /* Description of the quote */
        val description: kotlin.String? = null,
        /* This is the date wished by the requester to have the requested quote item(s) delivered */
        val expectedFulfillmentStartDate: java.time.LocalDateTime? = null,
        /* ID given by the consumer and only understandable by him (to facilitate his searches afterwards) */
        val externalId: kotlin.String? = null,
        /* If this flag is set to Yes, Buyer requests to have instant quoting to be provided in operation POST response */
        val instantSyncQuoting: kotlin.Boolean? = null,
        val note: kotlin.Array<Note>? = null,
        /* This value MAY be assigned by the Buyer/Seller to identify a project the quoting request is associated with. */
        val projectId: kotlin.String? = null,
        val quoteLevel: QuoteLevel? = null
) {

}

