/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * This structure is used to describe Quote item only in the POST operation for the request.
 * @param @schemaLocation Link to the schema describing this REST resource
 * @param @type Indicates the base (class) type of the quote Item.
 * @param action
 * @param id Identifier of the quote item (generally it is a sequence number 01, 02, 03, ...).
 * @param note
 * @param product
 * @param productOffering
 * @param qualification
 * @param quoteItemRelationship
 * @param relatedParty
 * @param requestedQuoteItemTerm
 */
data class QuoteItemCreate(
        val action: ProductActionType,
        /* Identifier of the quote item (generally it is a sequence number 01, 02, 03, ...). */
        val id: kotlin.String,
        /* Link to the schema describing this REST resource */
        val schemaLocation: kotlin.String? = null,
        /* Indicates the base (class) type of the quote Item. */
        val type: kotlin.String? = null,
        val note: kotlin.Array<Note>? = null,
        val product: Product? = null,
        val productOffering: ProductOfferingRef? = null,
        val qualification: ProductOfferingQualificationRef? = null,
        val quoteItemRelationship: kotlin.Array<QuoteItemRelationship>? = null,
        val relatedParty: kotlin.Array<RelatedParty>? = null,
        val requestedQuoteItemTerm: ItemTerm? = null
) {

}

