/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Used to describe relationship between quote item. These relationships could have an impact on pricing and conditions.
 * @param id ID of the related order item (must be in the same quote).
 * @param type
 */
data class QuoteItemRelationship(
        /* ID of the related order item (must be in the same quote). */
        val id: kotlin.String,
        val type: RelationshipType
) {

}

