/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * A globally unique identifier controlled by a generally accepted independent administrative authority that specifies a fixed geographical location.
 * @param id Unique identifier of the address
 * @param referenceId Id of a reference address
 * @param referenceType Type of a reference address
 */
data class ReferencedAddress(
        /* Id of a reference address */
        val referenceId: kotlin.String,
        /* Type of a reference address */
        val referenceType: kotlin.String,
        /* Unique identifier of the address */
        val id: kotlin.String? = null
) {

}

