/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Place defines the places where the products qualification must be done.
 * @param @referredType The actual type of the target instance when needed for disambiguation. Used when place is described by reference @referredType could be valued to FormattedAddress, FieldedAddress, GeographicSite, GeographicLocation or ReferencedAddress
 * @param @type When sub-classing, this defines the sub-class entity name. Used when place is described by value (litterally) Could be valued to FormattedAddress, FieldedAddress,  GeographicLocation or ReferencedAddress
 * @param href href to this place resource
 * @param id id of this place
 * @param role Role of this place
 */
data class RelatedPlaceReforValue(
        /* Role of this place */
        val role: kotlin.String,
        /* The actual type of the target instance when needed for disambiguation. Used when place is described by reference @referredType could be valued to FormattedAddress, FieldedAddress, GeographicSite, GeographicLocation or ReferencedAddress */
        val referredType: kotlin.String? = null,
        /* When sub-classing, this defines the sub-class entity name. Used when place is described by value (litterally) Could be valued to FormattedAddress, FieldedAddress,  GeographicLocation or ReferencedAddress */
        val type: kotlin.String? = null,
        /* href to this place resource */
        val href: kotlin.String? = null,
        /* id of this place */
        val id: kotlin.String? = null
) {

}

