/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * An entity or organization that is involved to the geographical site, such as the Site Contact or Site Alternate Contact.
 * @param @referredType Allow to specify the party type like Organization or Individual
 * @param emailAddress The email address of the related party.
 * @param id An identifier of the related party.
 * @param name The name of the related party, e.g. \"Jean Pontus\".
 * @param number The telephone number of the related party.
 * @param numberExtension Phone number Extension.
 * @param role Role played by this party for this Site as UNISiteContact for example.
 */
data class RelatedParty(
        /* An identifier of the related party. */
        val id: kotlin.String,
        /* The name of the related party, e.g. \"Jean Pontus\". */
        val name: kotlin.String,
        /* Role played by this party for this Site as UNISiteContact for example. */
        val role: kotlin.Array<kotlin.String>,
        /* Allow to specify the party type like Organization or Individual */
        val referredType: kotlin.String? = null,
        /* The email address of the related party. */
        val emailAddress: kotlin.String? = null,
        /* The telephone number of the related party. */
        val number: kotlin.String? = null,
        /* Phone number Extension. */
        val numberExtension: kotlin.String? = null
) {

}

