/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Place defines the places where the quoted products are sold or delivered
 * @param @type
 * @param href Unique reference of the place
 * @param id Unique identifier of the place
 * @param role The role that the place plays, e.g.  \"UNI Site\", or \"ENNI Site\".
 */
data class RelatedPlaceRefOrValue(
        /* The role that the place plays, e.g.  \"UNI Site\", or \"ENNI Site\". */
        val role: kotlin.String,
        val type: kotlin.String? = null,
        /* Unique reference of the place */
        val href: kotlin.String? = null,
        /* Unique identifier of the place */
        val id: kotlin.String? = null
) {

}

