/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

/**
 * Holds the status modification reasons and associated date the status changed, populated by the server
 * @param changeDate Date when the state changed
 * @param changeReason Raison for which the state changed
 * @param status
 */
data class StatusChange(
        /* Date when the state changed */
        val changeDate: java.time.LocalDateTime? = null,
        /* Raison for which the state changed */
        val changeReason: kotlin.String? = null,
        val status: ProductStatus? = null
) {

}

