/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 * Sub Unit structure is used to describe several subUnits with a geographical subAddress.
 * @param subUnitIdentifier The discriminator used for the subunit, often just a simple number but may also be a range.
 * @param subUnitType The type of subunit e.g.BERTH, FLAT, PIER, SUITE, SHOP, TOWER, UNIT, WHARF.
 */
data class SubUnit(
        /* The discriminator used for the subunit, often just a simple number but may also be a range. */
        val subUnitIdentifier: kotlin.String,
        /* The type of subunit e.g.BERTH, FLAT, PIER, SUITE, SHOP, TOWER, UNIT, WHARF. */
        val subUnitType: kotlin.String
) {

}

