/**
 * MEF LSO Sonata
 *  A set of APIs based on the LSO Reference Architecture for Serviceability (Address Validation, Site Queries, Product Offering Qualification) | Quoting | Product Inventory | Ordering | Trouble-ticketing Billing | Contract & Catalog
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.apis

// ktor 0.9.x is missing io.ktor.locations.DELETE, this adds it.
// see https://github.com/ktorio/ktor/issues/288

import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.auth.OAuthAccessTokenResponse
import io.ktor.auth.authentication
import io.ktor.auth.oauth
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.locations.get
import io.ktor.locations.oauthAtLocation
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.Route
import io.ktor.routing.application
import io.ktor.routing.post
import io.ktor.routing.route
import io.swagger.server.ApplicationAuthProviders
import io.swagger.server.ApplicationExecutors
import io.swagger.server.HTTP.client
import io.swagger.server.Paths
import kotlinx.coroutines.experimental.asCoroutineDispatcher

fun Route.ProductOrderApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()

    route("/productOrderManagement/v3/productOrder") {
        post {
            val principal = call.authentication.principal<OAuthAccessTokenResponse>()

            if (principal == null) {
                call.respond(HttpStatusCode.Unauthorized)
            } else {
                val exampleContentType = "application/json;charset=utf-8"
                val exampleContentString = """{
                  "pricingReference" : "pricingReference",
                  "relatedBuyerPON" : "relatedBuyerPON",
                  "note" : [ {
                    "date" : "2000-01-23T04:56:07.000+00:00",
                    "author" : "author",
                    "text" : "text"
                  }, {
                    "date" : "2000-01-23T04:56:07.000+00:00",
                    "author" : "author",
                    "text" : "text"
                  } ],
                  "buyerRequestDate" : "2000-01-23T04:56:07.000+00:00",
                  "@type" : "@type",
                  "billingAccount" : {
                    "id" : "id"
                  },
                  "pricingTerm" : 6,
                  "requestedStartDate" : "2000-01-23T04:56:07.000+00:00",
                  "@baseType" : "@baseType",
                  "desiredResponses" : { },
                  "expeditePriority" : true,
                  "href" : "href",
                  "id" : "id",
                  "state" : { },
                  "@schemaLocation" : "@schemaLocation",
                  "cancellationDate" : "2000-01-23T04:56:07.000+00:00",
                  "requestedCompletionDate" : "2000-01-23T04:56:07.000+00:00",
                  "cancellationReason" : "cancellationReason",
                  "orderItem" : [ {
                    "pricingReference" : "pricingReference",
                    "product" : {
                      "productSpecification" : {
                        "describing" : {
                          "@type" : "@type",
                          "@schemaLocation" : "@schemaLocation"
                        },
                        "id" : "id"
                      },
                      "agreement" : [ {
                        "path" : "path",
                        "name" : "name",
                        "id" : "id"
                      }, {
                        "path" : "path",
                        "name" : "name",
                        "id" : "id"
                      } ],
                      "productOffering" : {
                        "id" : "id"
                      },
                      "@type" : "@type",
                      "lastUpdateDate" : "2000-01-23T04:56:07.000+00:00",
                      "productOrder" : [ {
                        "orderItemId" : "orderItemId",
                        "href" : "href",
                        "id" : "id"
                      }, {
                        "orderItemId" : "orderItemId",
                        "href" : "href",
                        "id" : "id"
                      } ],
                      "billingAccount" : [ {
                        "id" : "id"
                      }, {
                        "id" : "id"
                      } ],
                      "productTerm" : [ {
                        "duration" : {
                          "amount" : 1.4658129,
                          "units" : "units"
                        },
                        "validFor" : {
                          "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                          "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                        },
                        "name" : "name",
                        "description" : "description"
                      }, {
                        "duration" : {
                          "amount" : 1.4658129,
                          "units" : "units"
                        },
                        "validFor" : {
                          "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                          "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                        },
                        "name" : "name",
                        "description" : "description"
                      } ],
                      "relatedParty" : [ {
                        "number" : "number",
                        "@referredType" : "@referredType",
                        "emailAddress" : "emailAddress",
                        "role" : [ "role", "role" ],
                        "name" : "name",
                        "numberExtension" : "numberExtension",
                        "id" : "id"
                      }, {
                        "number" : "number",
                        "@referredType" : "@referredType",
                        "emailAddress" : "emailAddress",
                        "role" : [ "role", "role" ],
                        "name" : "name",
                        "numberExtension" : "numberExtension",
                        "id" : "id"
                      } ],
                      "terminationDate" : "2000-01-23T04:56:07.000+00:00",
                      "site" : [ {
                        "geographicLocation" : {
                          "spatialRef" : "spatialRef",
                          "geographicPoint" : [ {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          }, {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          } ],
                          "id" : "id"
                        },
                        "referencedAddress" : {
                          "referenceType" : "referenceType",
                          "id" : "id",
                          "referenceId" : "referenceId"
                        },
                        "@type" : "@type",
                        "description" : "description",
                        "siteName" : "siteName",
                        "relatedParty" : [ {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        }, {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        } ],
                        "additionnalSiteInformation" : "additionnalSiteInformation",
                        "siteCompanyName" : "siteCompanyName",
                        "fieldedAddress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "streetType" : "streetType",
                          "city" : "city",
                          "streetNr" : "streetNr",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "streetNrLast" : "streetNrLast",
                          "streetNrSuffix" : "streetNrSuffix",
                          "streetName" : "streetName",
                          "stateOrProvince" : "stateOrProvince",
                          "streetNrLastSuffix" : "streetNrLastSuffix",
                          "geographicSubAddress" : [ {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          }, {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          } ],
                          "streetSuffix" : "streetSuffix",
                          "id" : "id"
                        },
                        "siteCustomerName" : "siteCustomerName",
                        "formattedAdress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "stateOrProvince" : "stateOrProvince",
                          "city" : "city",
                          "addrLine2" : "addrLine2",
                          "addrLine1" : "addrLine1",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "id" : "id"
                        },
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "siteType" : "siteType",
                        "status" : { }
                      }, {
                        "geographicLocation" : {
                          "spatialRef" : "spatialRef",
                          "geographicPoint" : [ {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          }, {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          } ],
                          "id" : "id"
                        },
                        "referencedAddress" : {
                          "referenceType" : "referenceType",
                          "id" : "id",
                          "referenceId" : "referenceId"
                        },
                        "@type" : "@type",
                        "description" : "description",
                        "siteName" : "siteName",
                        "relatedParty" : [ {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        }, {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        } ],
                        "additionnalSiteInformation" : "additionnalSiteInformation",
                        "siteCompanyName" : "siteCompanyName",
                        "fieldedAddress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "streetType" : "streetType",
                          "city" : "city",
                          "streetNr" : "streetNr",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "streetNrLast" : "streetNrLast",
                          "streetNrSuffix" : "streetNrSuffix",
                          "streetName" : "streetName",
                          "stateOrProvince" : "stateOrProvince",
                          "streetNrLastSuffix" : "streetNrLastSuffix",
                          "geographicSubAddress" : [ {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          }, {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          } ],
                          "streetSuffix" : "streetSuffix",
                          "id" : "id"
                        },
                        "siteCustomerName" : "siteCustomerName",
                        "formattedAdress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "stateOrProvince" : "stateOrProvince",
                          "city" : "city",
                          "addrLine2" : "addrLine2",
                          "addrLine1" : "addrLine1",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "id" : "id"
                        },
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "siteType" : "siteType",
                        "status" : { }
                      } ],
                      "@baseType" : "@baseType",
                      "statusChange" : [ {
                        "changeReason" : "changeReason",
                        "changeDate" : "2000-01-23T04:56:07.000+00:00"
                      }, {
                        "changeReason" : "changeReason",
                        "changeDate" : "2000-01-23T04:56:07.000+00:00"
                      } ],
                      "buyerProductId" : "buyerProductId",
                      "productRelationship" : [ {
                        "product" : {
                          "buyerProductId" : "buyerProductId",
                          "href" : "href",
                          "id" : "id"
                        },
                        "type" : "type"
                      }, {
                        "product" : {
                          "buyerProductId" : "buyerProductId",
                          "href" : "href",
                          "id" : "id"
                        },
                        "type" : "type"
                      } ],
                      "href" : "href",
                      "id" : "id",
                      "@schemaLocation" : "@schemaLocation",
                      "productPrice" : [ {
                        "unitOfMeasure" : "unitOfMeasure",
                        "@type" : "@type",
                        "price" : {
                          "taxRate" : 6.0274563,
                          "@type" : "@type",
                          "taxIncludedAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          },
                          "dutyFreeAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          }
                        },
                        "name" : "name",
                        "priceType" : { },
                        "description" : "description",
                        "recurringChargePeriod" : { }
                      }, {
                        "unitOfMeasure" : "unitOfMeasure",
                        "@type" : "@type",
                        "price" : {
                          "taxRate" : 6.0274563,
                          "@type" : "@type",
                          "taxIncludedAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          },
                          "dutyFreeAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          }
                        },
                        "name" : "name",
                        "priceType" : { },
                        "description" : "description",
                        "recurringChargePeriod" : { }
                      } ],
                      "startDate" : "2000-01-23T04:56:07.000+00:00",
                      "status" : { }
                    },
                    "productOffering" : {
                      "id" : "id"
                    },
                    "@type" : "@type",
                    "pricingMethod" : { },
                    "stateChange" : [ {
                      "changeReason" : "changeReason",
                      "changeDate" : "2000-01-23T04:56:07.000+00:00",
                      "state" : { }
                    }, {
                      "changeReason" : "changeReason",
                      "changeDate" : "2000-01-23T04:56:07.000+00:00",
                      "state" : { }
                    } ],
                    "billingAccount" : {
                      "id" : "id"
                    },
                    "relatedParty" : [ {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    }, {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    } ],
                    "pricingTerm" : 0,
                    "qualification" : {
                      "qualificationItem" : "qualificationItem",
                      "@referredType" : "@referredType",
                      "href" : "href",
                      "id" : "id"
                    },
                    "quote" : {
                      "@referredType" : "@referredType",
                      "quoteItem" : "quoteItem",
                      "href" : "href",
                      "id" : "id"
                    },
                    "action" : { },
                    "orderItemRelationship" : [ {
                      "productOrderId" : "productOrderId",
                      "id" : "id",
                      "type" : "type"
                    }, {
                      "productOrderId" : "productOrderId",
                      "id" : "id",
                      "type" : "type"
                    } ],
                    "id" : "id",
                    "state" : { },
                    "@schemaLocation" : "@schemaLocation",
                    "orderItemPrice" : [ {
                      "@type" : "@type",
                      "price" : {
                        "taxRate" : 6.0274563,
                        "@type" : "@type",
                        "taxIncludedAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        },
                        "dutyFreeAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        }
                      },
                      "name" : "name",
                      "priceType" : { },
                      "description" : "description",
                      "recurringChargePeriod" : { }
                    }, {
                      "@type" : "@type",
                      "price" : {
                        "taxRate" : 6.0274563,
                        "@type" : "@type",
                        "taxIncludedAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        },
                        "dutyFreeAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        }
                      },
                      "name" : "name",
                      "priceType" : { },
                      "description" : "description",
                      "recurringChargePeriod" : { }
                    } ]
                  }, {
                    "pricingReference" : "pricingReference",
                    "product" : {
                      "productSpecification" : {
                        "describing" : {
                          "@type" : "@type",
                          "@schemaLocation" : "@schemaLocation"
                        },
                        "id" : "id"
                      },
                      "agreement" : [ {
                        "path" : "path",
                        "name" : "name",
                        "id" : "id"
                      }, {
                        "path" : "path",
                        "name" : "name",
                        "id" : "id"
                      } ],
                      "productOffering" : {
                        "id" : "id"
                      },
                      "@type" : "@type",
                      "lastUpdateDate" : "2000-01-23T04:56:07.000+00:00",
                      "productOrder" : [ {
                        "orderItemId" : "orderItemId",
                        "href" : "href",
                        "id" : "id"
                      }, {
                        "orderItemId" : "orderItemId",
                        "href" : "href",
                        "id" : "id"
                      } ],
                      "billingAccount" : [ {
                        "id" : "id"
                      }, {
                        "id" : "id"
                      } ],
                      "productTerm" : [ {
                        "duration" : {
                          "amount" : 1.4658129,
                          "units" : "units"
                        },
                        "validFor" : {
                          "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                          "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                        },
                        "name" : "name",
                        "description" : "description"
                      }, {
                        "duration" : {
                          "amount" : 1.4658129,
                          "units" : "units"
                        },
                        "validFor" : {
                          "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                          "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                        },
                        "name" : "name",
                        "description" : "description"
                      } ],
                      "relatedParty" : [ {
                        "number" : "number",
                        "@referredType" : "@referredType",
                        "emailAddress" : "emailAddress",
                        "role" : [ "role", "role" ],
                        "name" : "name",
                        "numberExtension" : "numberExtension",
                        "id" : "id"
                      }, {
                        "number" : "number",
                        "@referredType" : "@referredType",
                        "emailAddress" : "emailAddress",
                        "role" : [ "role", "role" ],
                        "name" : "name",
                        "numberExtension" : "numberExtension",
                        "id" : "id"
                      } ],
                      "terminationDate" : "2000-01-23T04:56:07.000+00:00",
                      "site" : [ {
                        "geographicLocation" : {
                          "spatialRef" : "spatialRef",
                          "geographicPoint" : [ {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          }, {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          } ],
                          "id" : "id"
                        },
                        "referencedAddress" : {
                          "referenceType" : "referenceType",
                          "id" : "id",
                          "referenceId" : "referenceId"
                        },
                        "@type" : "@type",
                        "description" : "description",
                        "siteName" : "siteName",
                        "relatedParty" : [ {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        }, {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        } ],
                        "additionnalSiteInformation" : "additionnalSiteInformation",
                        "siteCompanyName" : "siteCompanyName",
                        "fieldedAddress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "streetType" : "streetType",
                          "city" : "city",
                          "streetNr" : "streetNr",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "streetNrLast" : "streetNrLast",
                          "streetNrSuffix" : "streetNrSuffix",
                          "streetName" : "streetName",
                          "stateOrProvince" : "stateOrProvince",
                          "streetNrLastSuffix" : "streetNrLastSuffix",
                          "geographicSubAddress" : [ {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          }, {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          } ],
                          "streetSuffix" : "streetSuffix",
                          "id" : "id"
                        },
                        "siteCustomerName" : "siteCustomerName",
                        "formattedAdress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "stateOrProvince" : "stateOrProvince",
                          "city" : "city",
                          "addrLine2" : "addrLine2",
                          "addrLine1" : "addrLine1",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "id" : "id"
                        },
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "siteType" : "siteType",
                        "status" : { }
                      }, {
                        "geographicLocation" : {
                          "spatialRef" : "spatialRef",
                          "geographicPoint" : [ {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          }, {
                            "latitude" : "latitude",
                            "id" : "id",
                            "longitude" : "longitude"
                          } ],
                          "id" : "id"
                        },
                        "referencedAddress" : {
                          "referenceType" : "referenceType",
                          "id" : "id",
                          "referenceId" : "referenceId"
                        },
                        "@type" : "@type",
                        "description" : "description",
                        "siteName" : "siteName",
                        "relatedParty" : [ {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        }, {
                          "number" : "number",
                          "@referredType" : "@referredType",
                          "emailAddress" : "emailAddress",
                          "role" : [ "role", "role" ],
                          "name" : "name",
                          "numberExtension" : "numberExtension",
                          "id" : "id"
                        } ],
                        "additionnalSiteInformation" : "additionnalSiteInformation",
                        "siteCompanyName" : "siteCompanyName",
                        "fieldedAddress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "streetType" : "streetType",
                          "city" : "city",
                          "streetNr" : "streetNr",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "streetNrLast" : "streetNrLast",
                          "streetNrSuffix" : "streetNrSuffix",
                          "streetName" : "streetName",
                          "stateOrProvince" : "stateOrProvince",
                          "streetNrLastSuffix" : "streetNrLastSuffix",
                          "geographicSubAddress" : [ {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          }, {
                            "buildingName" : "buildingName",
                            "subUnit" : [ {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            }, {
                              "subUnitType" : "subUnitType",
                              "subUnitIdentifier" : "subUnitIdentifier"
                            } ],
                            "@type" : "@type",
                            "levelType" : "levelType",
                            "levelNumber" : "levelNumber",
                            "id" : "id",
                            "@schemaLocation" : "@schemaLocation",
                            "privateStreetNumber" : "privateStreetNumber",
                            "privateStreetName" : "privateStreetName"
                          } ],
                          "streetSuffix" : "streetSuffix",
                          "id" : "id"
                        },
                        "siteCustomerName" : "siteCustomerName",
                        "formattedAdress" : {
                          "country" : "country",
                          "postCodeExtension" : "postCodeExtension",
                          "stateOrProvince" : "stateOrProvince",
                          "city" : "city",
                          "addrLine2" : "addrLine2",
                          "addrLine1" : "addrLine1",
                          "locality" : "locality",
                          "postcode" : "postcode",
                          "id" : "id"
                        },
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "siteType" : "siteType",
                        "status" : { }
                      } ],
                      "@baseType" : "@baseType",
                      "statusChange" : [ {
                        "changeReason" : "changeReason",
                        "changeDate" : "2000-01-23T04:56:07.000+00:00"
                      }, {
                        "changeReason" : "changeReason",
                        "changeDate" : "2000-01-23T04:56:07.000+00:00"
                      } ],
                      "buyerProductId" : "buyerProductId",
                      "productRelationship" : [ {
                        "product" : {
                          "buyerProductId" : "buyerProductId",
                          "href" : "href",
                          "id" : "id"
                        },
                        "type" : "type"
                      }, {
                        "product" : {
                          "buyerProductId" : "buyerProductId",
                          "href" : "href",
                          "id" : "id"
                        },
                        "type" : "type"
                      } ],
                      "href" : "href",
                      "id" : "id",
                      "@schemaLocation" : "@schemaLocation",
                      "productPrice" : [ {
                        "unitOfMeasure" : "unitOfMeasure",
                        "@type" : "@type",
                        "price" : {
                          "taxRate" : 6.0274563,
                          "@type" : "@type",
                          "taxIncludedAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          },
                          "dutyFreeAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          }
                        },
                        "name" : "name",
                        "priceType" : { },
                        "description" : "description",
                        "recurringChargePeriod" : { }
                      }, {
                        "unitOfMeasure" : "unitOfMeasure",
                        "@type" : "@type",
                        "price" : {
                          "taxRate" : 6.0274563,
                          "@type" : "@type",
                          "taxIncludedAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          },
                          "dutyFreeAmount" : {
                            "unit" : "unit",
                            "value" : 0.8008282
                          }
                        },
                        "name" : "name",
                        "priceType" : { },
                        "description" : "description",
                        "recurringChargePeriod" : { }
                      } ],
                      "startDate" : "2000-01-23T04:56:07.000+00:00",
                      "status" : { }
                    },
                    "productOffering" : {
                      "id" : "id"
                    },
                    "@type" : "@type",
                    "pricingMethod" : { },
                    "stateChange" : [ {
                      "changeReason" : "changeReason",
                      "changeDate" : "2000-01-23T04:56:07.000+00:00",
                      "state" : { }
                    }, {
                      "changeReason" : "changeReason",
                      "changeDate" : "2000-01-23T04:56:07.000+00:00",
                      "state" : { }
                    } ],
                    "billingAccount" : {
                      "id" : "id"
                    },
                    "relatedParty" : [ {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    }, {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    } ],
                    "pricingTerm" : 0,
                    "qualification" : {
                      "qualificationItem" : "qualificationItem",
                      "@referredType" : "@referredType",
                      "href" : "href",
                      "id" : "id"
                    },
                    "quote" : {
                      "@referredType" : "@referredType",
                      "quoteItem" : "quoteItem",
                      "href" : "href",
                      "id" : "id"
                    },
                    "action" : { },
                    "orderItemRelationship" : [ {
                      "productOrderId" : "productOrderId",
                      "id" : "id",
                      "type" : "type"
                    }, {
                      "productOrderId" : "productOrderId",
                      "id" : "id",
                      "type" : "type"
                    } ],
                    "id" : "id",
                    "state" : { },
                    "@schemaLocation" : "@schemaLocation",
                    "orderItemPrice" : [ {
                      "@type" : "@type",
                      "price" : {
                        "taxRate" : 6.0274563,
                        "@type" : "@type",
                        "taxIncludedAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        },
                        "dutyFreeAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        }
                      },
                      "name" : "name",
                      "priceType" : { },
                      "description" : "description",
                      "recurringChargePeriod" : { }
                    }, {
                      "@type" : "@type",
                      "price" : {
                        "taxRate" : 6.0274563,
                        "@type" : "@type",
                        "taxIncludedAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        },
                        "dutyFreeAmount" : {
                          "unit" : "unit",
                          "value" : 0.8008282
                        }
                      },
                      "name" : "name",
                      "priceType" : { },
                      "description" : "description",
                      "recurringChargePeriod" : { }
                    } ]
                  } ],
                  "orderActivity" : { },
                  "externalId" : "externalId",
                  "stateChange" : [ {
                    "changeReason" : "changeReason",
                    "changeDate" : "2000-01-23T04:56:07.000+00:00",
                    "state" : { }
                  }, {
                    "changeReason" : "changeReason",
                    "changeDate" : "2000-01-23T04:56:07.000+00:00",
                    "state" : { }
                  } ],
                  "orderVersion" : "1",
                  "priority" : 1,
                  "relatedParty" : [ {
                    "number" : "number",
                    "@referredType" : "@referredType",
                    "emailAddress" : "emailAddress",
                    "role" : [ "role", "role" ],
                    "name" : "name",
                    "numberExtension" : "numberExtension",
                    "id" : "id"
                  }, {
                    "number" : "number",
                    "@referredType" : "@referredType",
                    "emailAddress" : "emailAddress",
                    "role" : [ "role", "role" ],
                    "name" : "name",
                    "numberExtension" : "numberExtension",
                    "id" : "id"
                  } ],
                  "orderMessage" : [ {
                    "severity" : { },
                    "correctionRequired" : false,
                    "code" : "code",
                    "field" : "field",
                    "messageInformation" : "messageInformation"
                  }, {
                    "severity" : { },
                    "correctionRequired" : false,
                    "code" : "code",
                    "field" : "field",
                    "messageInformation" : "messageInformation"
                  } ],
                  "tspRestorationPriority" : "tspRestorationPriority",
                  "completionDate" : "2000-01-23T04:56:07.000+00:00",
                  "expectedCompletionDate" : "2000-01-23T04:56:07.000+00:00",
                  "orderDate" : "2000-01-23T04:56:07.000+00:00",
                  "projectId" : "projectId"
                }"""

                when (exampleContentType) {
                    "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
                    "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
                    else -> call.respondText(exampleContentString)
                }
            }
        }
    }
            .apply {
                // TODO: ktor doesn't allow different authentication registrations for endpoints sharing the same path but different methods.
                //       It could be the authentication block is being abused here. Until this is resolved, swallow duplicate exceptions.

                try {
                    authentication {
                        oauth(client, ApplicationExecutors.asCoroutineDispatcher(), { ApplicationAuthProviders["bearer"] }, {
                            // TODO: define a callback url here.
                            "/"
                        })
                    }
                } catch (e: io.ktor.application.DuplicateApplicationFeatureException) {
                    application.environment.log.warn("authentication block for '/productOrderManagement/v3/productOrder' is duplicated in code. " +
                            "Generated endpoints may need to be merged under a 'route' entry.")
                }
            }

    get<Paths.productOrderFind> { it: Paths.productOrderFind ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

        if (principal == null) {
            call.respond(HttpStatusCode.Unauthorized)
        } else {
            val exampleContentType = "application/json;charset=utf-8"
            val exampleContentString = """[ {
              "externalId" : "externalId",
              "id" : "id",
              "state" : { },
              "orderDate" : "2000-01-23T04:56:07.000+00:00"
            }, {
              "externalId" : "externalId",
              "id" : "id",
              "state" : { },
              "orderDate" : "2000-01-23T04:56:07.000+00:00"
            } ]"""

            when (exampleContentType) {
                "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
                "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
                else -> call.respondText(exampleContentString)
            }
        }
    }
            .apply {
                // TODO: ktor doesn't allow different authentication registrations for endpoints sharing the same path but different methods.
                //       It could be the authentication block is being abused here. Until this is resolved, swallow duplicate exceptions.

                try {
                    authentication {
                        oauthAtLocation<Paths.productOrderFind>(client, ApplicationExecutors.asCoroutineDispatcher(),
                                providerLookup = { ApplicationAuthProviders["bearer"] },
                                urlProvider = { currentLocation, provider ->
                                    // TODO: define a callback url here.
                                    "/"
                                })
                    }
                } catch (e: io.ktor.application.DuplicateApplicationFeatureException) {
                    application.environment.log.warn("authentication block for '/productOrderManagement/v3/productOrder' is duplicated in code. " +
                            "Generated endpoints may need to be merged under a 'route' entry.")
                }
            }

    get<Paths.productOrderGet> { it: Paths.productOrderGet ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

        if (principal == null) {
            call.respond(HttpStatusCode.Unauthorized)
        } else {
            val exampleContentType = "application/json;charset=utf-8"
            val exampleContentString = """{
              "pricingReference" : "pricingReference",
              "relatedBuyerPON" : "relatedBuyerPON",
              "note" : [ {
                "date" : "2000-01-23T04:56:07.000+00:00",
                "author" : "author",
                "text" : "text"
              }, {
                "date" : "2000-01-23T04:56:07.000+00:00",
                "author" : "author",
                "text" : "text"
              } ],
              "buyerRequestDate" : "2000-01-23T04:56:07.000+00:00",
              "@type" : "@type",
              "billingAccount" : {
                "id" : "id"
              },
              "pricingTerm" : 6,
              "requestedStartDate" : "2000-01-23T04:56:07.000+00:00",
              "@baseType" : "@baseType",
              "desiredResponses" : { },
              "expeditePriority" : true,
              "href" : "href",
              "id" : "id",
              "state" : { },
              "@schemaLocation" : "@schemaLocation",
              "cancellationDate" : "2000-01-23T04:56:07.000+00:00",
              "requestedCompletionDate" : "2000-01-23T04:56:07.000+00:00",
              "cancellationReason" : "cancellationReason",
              "orderItem" : [ {
                "pricingReference" : "pricingReference",
                "product" : {
                  "productSpecification" : {
                    "describing" : {
                      "@type" : "@type",
                      "@schemaLocation" : "@schemaLocation"
                    },
                    "id" : "id"
                  },
                  "agreement" : [ {
                    "path" : "path",
                    "name" : "name",
                    "id" : "id"
                  }, {
                    "path" : "path",
                    "name" : "name",
                    "id" : "id"
                  } ],
                  "productOffering" : {
                    "id" : "id"
                  },
                  "@type" : "@type",
                  "lastUpdateDate" : "2000-01-23T04:56:07.000+00:00",
                  "productOrder" : [ {
                    "orderItemId" : "orderItemId",
                    "href" : "href",
                    "id" : "id"
                  }, {
                    "orderItemId" : "orderItemId",
                    "href" : "href",
                    "id" : "id"
                  } ],
                  "billingAccount" : [ {
                    "id" : "id"
                  }, {
                    "id" : "id"
                  } ],
                  "productTerm" : [ {
                    "duration" : {
                      "amount" : 1.4658129,
                      "units" : "units"
                    },
                    "validFor" : {
                      "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                      "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                    },
                    "name" : "name",
                    "description" : "description"
                  }, {
                    "duration" : {
                      "amount" : 1.4658129,
                      "units" : "units"
                    },
                    "validFor" : {
                      "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                      "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                    },
                    "name" : "name",
                    "description" : "description"
                  } ],
                  "relatedParty" : [ {
                    "number" : "number",
                    "@referredType" : "@referredType",
                    "emailAddress" : "emailAddress",
                    "role" : [ "role", "role" ],
                    "name" : "name",
                    "numberExtension" : "numberExtension",
                    "id" : "id"
                  }, {
                    "number" : "number",
                    "@referredType" : "@referredType",
                    "emailAddress" : "emailAddress",
                    "role" : [ "role", "role" ],
                    "name" : "name",
                    "numberExtension" : "numberExtension",
                    "id" : "id"
                  } ],
                  "terminationDate" : "2000-01-23T04:56:07.000+00:00",
                  "site" : [ {
                    "geographicLocation" : {
                      "spatialRef" : "spatialRef",
                      "geographicPoint" : [ {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      }, {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      } ],
                      "id" : "id"
                    },
                    "referencedAddress" : {
                      "referenceType" : "referenceType",
                      "id" : "id",
                      "referenceId" : "referenceId"
                    },
                    "@type" : "@type",
                    "description" : "description",
                    "siteName" : "siteName",
                    "relatedParty" : [ {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    }, {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    } ],
                    "additionnalSiteInformation" : "additionnalSiteInformation",
                    "siteCompanyName" : "siteCompanyName",
                    "fieldedAddress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "streetType" : "streetType",
                      "city" : "city",
                      "streetNr" : "streetNr",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "streetNrLast" : "streetNrLast",
                      "streetNrSuffix" : "streetNrSuffix",
                      "streetName" : "streetName",
                      "stateOrProvince" : "stateOrProvince",
                      "streetNrLastSuffix" : "streetNrLastSuffix",
                      "geographicSubAddress" : [ {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      }, {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      } ],
                      "streetSuffix" : "streetSuffix",
                      "id" : "id"
                    },
                    "siteCustomerName" : "siteCustomerName",
                    "formattedAdress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "stateOrProvince" : "stateOrProvince",
                      "city" : "city",
                      "addrLine2" : "addrLine2",
                      "addrLine1" : "addrLine1",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "id" : "id"
                    },
                    "id" : "id",
                    "@schemaLocation" : "@schemaLocation",
                    "siteType" : "siteType",
                    "status" : { }
                  }, {
                    "geographicLocation" : {
                      "spatialRef" : "spatialRef",
                      "geographicPoint" : [ {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      }, {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      } ],
                      "id" : "id"
                    },
                    "referencedAddress" : {
                      "referenceType" : "referenceType",
                      "id" : "id",
                      "referenceId" : "referenceId"
                    },
                    "@type" : "@type",
                    "description" : "description",
                    "siteName" : "siteName",
                    "relatedParty" : [ {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    }, {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    } ],
                    "additionnalSiteInformation" : "additionnalSiteInformation",
                    "siteCompanyName" : "siteCompanyName",
                    "fieldedAddress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "streetType" : "streetType",
                      "city" : "city",
                      "streetNr" : "streetNr",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "streetNrLast" : "streetNrLast",
                      "streetNrSuffix" : "streetNrSuffix",
                      "streetName" : "streetName",
                      "stateOrProvince" : "stateOrProvince",
                      "streetNrLastSuffix" : "streetNrLastSuffix",
                      "geographicSubAddress" : [ {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      }, {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      } ],
                      "streetSuffix" : "streetSuffix",
                      "id" : "id"
                    },
                    "siteCustomerName" : "siteCustomerName",
                    "formattedAdress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "stateOrProvince" : "stateOrProvince",
                      "city" : "city",
                      "addrLine2" : "addrLine2",
                      "addrLine1" : "addrLine1",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "id" : "id"
                    },
                    "id" : "id",
                    "@schemaLocation" : "@schemaLocation",
                    "siteType" : "siteType",
                    "status" : { }
                  } ],
                  "@baseType" : "@baseType",
                  "statusChange" : [ {
                    "changeReason" : "changeReason",
                    "changeDate" : "2000-01-23T04:56:07.000+00:00"
                  }, {
                    "changeReason" : "changeReason",
                    "changeDate" : "2000-01-23T04:56:07.000+00:00"
                  } ],
                  "buyerProductId" : "buyerProductId",
                  "productRelationship" : [ {
                    "product" : {
                      "buyerProductId" : "buyerProductId",
                      "href" : "href",
                      "id" : "id"
                    },
                    "type" : "type"
                  }, {
                    "product" : {
                      "buyerProductId" : "buyerProductId",
                      "href" : "href",
                      "id" : "id"
                    },
                    "type" : "type"
                  } ],
                  "href" : "href",
                  "id" : "id",
                  "@schemaLocation" : "@schemaLocation",
                  "productPrice" : [ {
                    "unitOfMeasure" : "unitOfMeasure",
                    "@type" : "@type",
                    "price" : {
                      "taxRate" : 6.0274563,
                      "@type" : "@type",
                      "taxIncludedAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      },
                      "dutyFreeAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      }
                    },
                    "name" : "name",
                    "priceType" : { },
                    "description" : "description",
                    "recurringChargePeriod" : { }
                  }, {
                    "unitOfMeasure" : "unitOfMeasure",
                    "@type" : "@type",
                    "price" : {
                      "taxRate" : 6.0274563,
                      "@type" : "@type",
                      "taxIncludedAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      },
                      "dutyFreeAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      }
                    },
                    "name" : "name",
                    "priceType" : { },
                    "description" : "description",
                    "recurringChargePeriod" : { }
                  } ],
                  "startDate" : "2000-01-23T04:56:07.000+00:00",
                  "status" : { }
                },
                "productOffering" : {
                  "id" : "id"
                },
                "@type" : "@type",
                "pricingMethod" : { },
                "stateChange" : [ {
                  "changeReason" : "changeReason",
                  "changeDate" : "2000-01-23T04:56:07.000+00:00",
                  "state" : { }
                }, {
                  "changeReason" : "changeReason",
                  "changeDate" : "2000-01-23T04:56:07.000+00:00",
                  "state" : { }
                } ],
                "billingAccount" : {
                  "id" : "id"
                },
                "relatedParty" : [ {
                  "number" : "number",
                  "@referredType" : "@referredType",
                  "emailAddress" : "emailAddress",
                  "role" : [ "role", "role" ],
                  "name" : "name",
                  "numberExtension" : "numberExtension",
                  "id" : "id"
                }, {
                  "number" : "number",
                  "@referredType" : "@referredType",
                  "emailAddress" : "emailAddress",
                  "role" : [ "role", "role" ],
                  "name" : "name",
                  "numberExtension" : "numberExtension",
                  "id" : "id"
                } ],
                "pricingTerm" : 0,
                "qualification" : {
                  "qualificationItem" : "qualificationItem",
                  "@referredType" : "@referredType",
                  "href" : "href",
                  "id" : "id"
                },
                "quote" : {
                  "@referredType" : "@referredType",
                  "quoteItem" : "quoteItem",
                  "href" : "href",
                  "id" : "id"
                },
                "action" : { },
                "orderItemRelationship" : [ {
                  "productOrderId" : "productOrderId",
                  "id" : "id",
                  "type" : "type"
                }, {
                  "productOrderId" : "productOrderId",
                  "id" : "id",
                  "type" : "type"
                } ],
                "id" : "id",
                "state" : { },
                "@schemaLocation" : "@schemaLocation",
                "orderItemPrice" : [ {
                  "@type" : "@type",
                  "price" : {
                    "taxRate" : 6.0274563,
                    "@type" : "@type",
                    "taxIncludedAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    },
                    "dutyFreeAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    }
                  },
                  "name" : "name",
                  "priceType" : { },
                  "description" : "description",
                  "recurringChargePeriod" : { }
                }, {
                  "@type" : "@type",
                  "price" : {
                    "taxRate" : 6.0274563,
                    "@type" : "@type",
                    "taxIncludedAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    },
                    "dutyFreeAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    }
                  },
                  "name" : "name",
                  "priceType" : { },
                  "description" : "description",
                  "recurringChargePeriod" : { }
                } ]
              }, {
                "pricingReference" : "pricingReference",
                "product" : {
                  "productSpecification" : {
                    "describing" : {
                      "@type" : "@type",
                      "@schemaLocation" : "@schemaLocation"
                    },
                    "id" : "id"
                  },
                  "agreement" : [ {
                    "path" : "path",
                    "name" : "name",
                    "id" : "id"
                  }, {
                    "path" : "path",
                    "name" : "name",
                    "id" : "id"
                  } ],
                  "productOffering" : {
                    "id" : "id"
                  },
                  "@type" : "@type",
                  "lastUpdateDate" : "2000-01-23T04:56:07.000+00:00",
                  "productOrder" : [ {
                    "orderItemId" : "orderItemId",
                    "href" : "href",
                    "id" : "id"
                  }, {
                    "orderItemId" : "orderItemId",
                    "href" : "href",
                    "id" : "id"
                  } ],
                  "billingAccount" : [ {
                    "id" : "id"
                  }, {
                    "id" : "id"
                  } ],
                  "productTerm" : [ {
                    "duration" : {
                      "amount" : 1.4658129,
                      "units" : "units"
                    },
                    "validFor" : {
                      "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                      "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                    },
                    "name" : "name",
                    "description" : "description"
                  }, {
                    "duration" : {
                      "amount" : 1.4658129,
                      "units" : "units"
                    },
                    "validFor" : {
                      "startDateTime" : "2000-01-23T04:56:07.000+00:00",
                      "endDateTime" : "2000-01-23T04:56:07.000+00:00"
                    },
                    "name" : "name",
                    "description" : "description"
                  } ],
                  "relatedParty" : [ {
                    "number" : "number",
                    "@referredType" : "@referredType",
                    "emailAddress" : "emailAddress",
                    "role" : [ "role", "role" ],
                    "name" : "name",
                    "numberExtension" : "numberExtension",
                    "id" : "id"
                  }, {
                    "number" : "number",
                    "@referredType" : "@referredType",
                    "emailAddress" : "emailAddress",
                    "role" : [ "role", "role" ],
                    "name" : "name",
                    "numberExtension" : "numberExtension",
                    "id" : "id"
                  } ],
                  "terminationDate" : "2000-01-23T04:56:07.000+00:00",
                  "site" : [ {
                    "geographicLocation" : {
                      "spatialRef" : "spatialRef",
                      "geographicPoint" : [ {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      }, {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      } ],
                      "id" : "id"
                    },
                    "referencedAddress" : {
                      "referenceType" : "referenceType",
                      "id" : "id",
                      "referenceId" : "referenceId"
                    },
                    "@type" : "@type",
                    "description" : "description",
                    "siteName" : "siteName",
                    "relatedParty" : [ {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    }, {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    } ],
                    "additionnalSiteInformation" : "additionnalSiteInformation",
                    "siteCompanyName" : "siteCompanyName",
                    "fieldedAddress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "streetType" : "streetType",
                      "city" : "city",
                      "streetNr" : "streetNr",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "streetNrLast" : "streetNrLast",
                      "streetNrSuffix" : "streetNrSuffix",
                      "streetName" : "streetName",
                      "stateOrProvince" : "stateOrProvince",
                      "streetNrLastSuffix" : "streetNrLastSuffix",
                      "geographicSubAddress" : [ {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      }, {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      } ],
                      "streetSuffix" : "streetSuffix",
                      "id" : "id"
                    },
                    "siteCustomerName" : "siteCustomerName",
                    "formattedAdress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "stateOrProvince" : "stateOrProvince",
                      "city" : "city",
                      "addrLine2" : "addrLine2",
                      "addrLine1" : "addrLine1",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "id" : "id"
                    },
                    "id" : "id",
                    "@schemaLocation" : "@schemaLocation",
                    "siteType" : "siteType",
                    "status" : { }
                  }, {
                    "geographicLocation" : {
                      "spatialRef" : "spatialRef",
                      "geographicPoint" : [ {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      }, {
                        "latitude" : "latitude",
                        "id" : "id",
                        "longitude" : "longitude"
                      } ],
                      "id" : "id"
                    },
                    "referencedAddress" : {
                      "referenceType" : "referenceType",
                      "id" : "id",
                      "referenceId" : "referenceId"
                    },
                    "@type" : "@type",
                    "description" : "description",
                    "siteName" : "siteName",
                    "relatedParty" : [ {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    }, {
                      "number" : "number",
                      "@referredType" : "@referredType",
                      "emailAddress" : "emailAddress",
                      "role" : [ "role", "role" ],
                      "name" : "name",
                      "numberExtension" : "numberExtension",
                      "id" : "id"
                    } ],
                    "additionnalSiteInformation" : "additionnalSiteInformation",
                    "siteCompanyName" : "siteCompanyName",
                    "fieldedAddress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "streetType" : "streetType",
                      "city" : "city",
                      "streetNr" : "streetNr",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "streetNrLast" : "streetNrLast",
                      "streetNrSuffix" : "streetNrSuffix",
                      "streetName" : "streetName",
                      "stateOrProvince" : "stateOrProvince",
                      "streetNrLastSuffix" : "streetNrLastSuffix",
                      "geographicSubAddress" : [ {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      }, {
                        "buildingName" : "buildingName",
                        "subUnit" : [ {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        }, {
                          "subUnitType" : "subUnitType",
                          "subUnitIdentifier" : "subUnitIdentifier"
                        } ],
                        "@type" : "@type",
                        "levelType" : "levelType",
                        "levelNumber" : "levelNumber",
                        "id" : "id",
                        "@schemaLocation" : "@schemaLocation",
                        "privateStreetNumber" : "privateStreetNumber",
                        "privateStreetName" : "privateStreetName"
                      } ],
                      "streetSuffix" : "streetSuffix",
                      "id" : "id"
                    },
                    "siteCustomerName" : "siteCustomerName",
                    "formattedAdress" : {
                      "country" : "country",
                      "postCodeExtension" : "postCodeExtension",
                      "stateOrProvince" : "stateOrProvince",
                      "city" : "city",
                      "addrLine2" : "addrLine2",
                      "addrLine1" : "addrLine1",
                      "locality" : "locality",
                      "postcode" : "postcode",
                      "id" : "id"
                    },
                    "id" : "id",
                    "@schemaLocation" : "@schemaLocation",
                    "siteType" : "siteType",
                    "status" : { }
                  } ],
                  "@baseType" : "@baseType",
                  "statusChange" : [ {
                    "changeReason" : "changeReason",
                    "changeDate" : "2000-01-23T04:56:07.000+00:00"
                  }, {
                    "changeReason" : "changeReason",
                    "changeDate" : "2000-01-23T04:56:07.000+00:00"
                  } ],
                  "buyerProductId" : "buyerProductId",
                  "productRelationship" : [ {
                    "product" : {
                      "buyerProductId" : "buyerProductId",
                      "href" : "href",
                      "id" : "id"
                    },
                    "type" : "type"
                  }, {
                    "product" : {
                      "buyerProductId" : "buyerProductId",
                      "href" : "href",
                      "id" : "id"
                    },
                    "type" : "type"
                  } ],
                  "href" : "href",
                  "id" : "id",
                  "@schemaLocation" : "@schemaLocation",
                  "productPrice" : [ {
                    "unitOfMeasure" : "unitOfMeasure",
                    "@type" : "@type",
                    "price" : {
                      "taxRate" : 6.0274563,
                      "@type" : "@type",
                      "taxIncludedAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      },
                      "dutyFreeAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      }
                    },
                    "name" : "name",
                    "priceType" : { },
                    "description" : "description",
                    "recurringChargePeriod" : { }
                  }, {
                    "unitOfMeasure" : "unitOfMeasure",
                    "@type" : "@type",
                    "price" : {
                      "taxRate" : 6.0274563,
                      "@type" : "@type",
                      "taxIncludedAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      },
                      "dutyFreeAmount" : {
                        "unit" : "unit",
                        "value" : 0.8008282
                      }
                    },
                    "name" : "name",
                    "priceType" : { },
                    "description" : "description",
                    "recurringChargePeriod" : { }
                  } ],
                  "startDate" : "2000-01-23T04:56:07.000+00:00",
                  "status" : { }
                },
                "productOffering" : {
                  "id" : "id"
                },
                "@type" : "@type",
                "pricingMethod" : { },
                "stateChange" : [ {
                  "changeReason" : "changeReason",
                  "changeDate" : "2000-01-23T04:56:07.000+00:00",
                  "state" : { }
                }, {
                  "changeReason" : "changeReason",
                  "changeDate" : "2000-01-23T04:56:07.000+00:00",
                  "state" : { }
                } ],
                "billingAccount" : {
                  "id" : "id"
                },
                "relatedParty" : [ {
                  "number" : "number",
                  "@referredType" : "@referredType",
                  "emailAddress" : "emailAddress",
                  "role" : [ "role", "role" ],
                  "name" : "name",
                  "numberExtension" : "numberExtension",
                  "id" : "id"
                }, {
                  "number" : "number",
                  "@referredType" : "@referredType",
                  "emailAddress" : "emailAddress",
                  "role" : [ "role", "role" ],
                  "name" : "name",
                  "numberExtension" : "numberExtension",
                  "id" : "id"
                } ],
                "pricingTerm" : 0,
                "qualification" : {
                  "qualificationItem" : "qualificationItem",
                  "@referredType" : "@referredType",
                  "href" : "href",
                  "id" : "id"
                },
                "quote" : {
                  "@referredType" : "@referredType",
                  "quoteItem" : "quoteItem",
                  "href" : "href",
                  "id" : "id"
                },
                "action" : { },
                "orderItemRelationship" : [ {
                  "productOrderId" : "productOrderId",
                  "id" : "id",
                  "type" : "type"
                }, {
                  "productOrderId" : "productOrderId",
                  "id" : "id",
                  "type" : "type"
                } ],
                "id" : "id",
                "state" : { },
                "@schemaLocation" : "@schemaLocation",
                "orderItemPrice" : [ {
                  "@type" : "@type",
                  "price" : {
                    "taxRate" : 6.0274563,
                    "@type" : "@type",
                    "taxIncludedAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    },
                    "dutyFreeAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    }
                  },
                  "name" : "name",
                  "priceType" : { },
                  "description" : "description",
                  "recurringChargePeriod" : { }
                }, {
                  "@type" : "@type",
                  "price" : {
                    "taxRate" : 6.0274563,
                    "@type" : "@type",
                    "taxIncludedAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    },
                    "dutyFreeAmount" : {
                      "unit" : "unit",
                      "value" : 0.8008282
                    }
                  },
                  "name" : "name",
                  "priceType" : { },
                  "description" : "description",
                  "recurringChargePeriod" : { }
                } ]
              } ],
              "orderActivity" : { },
              "externalId" : "externalId",
              "stateChange" : [ {
                "changeReason" : "changeReason",
                "changeDate" : "2000-01-23T04:56:07.000+00:00",
                "state" : { }
              }, {
                "changeReason" : "changeReason",
                "changeDate" : "2000-01-23T04:56:07.000+00:00",
                "state" : { }
              } ],
              "orderVersion" : "1",
              "priority" : 1,
              "relatedParty" : [ {
                "number" : "number",
                "@referredType" : "@referredType",
                "emailAddress" : "emailAddress",
                "role" : [ "role", "role" ],
                "name" : "name",
                "numberExtension" : "numberExtension",
                "id" : "id"
              }, {
                "number" : "number",
                "@referredType" : "@referredType",
                "emailAddress" : "emailAddress",
                "role" : [ "role", "role" ],
                "name" : "name",
                "numberExtension" : "numberExtension",
                "id" : "id"
              } ],
              "orderMessage" : [ {
                "severity" : { },
                "correctionRequired" : false,
                "code" : "code",
                "field" : "field",
                "messageInformation" : "messageInformation"
              }, {
                "severity" : { },
                "correctionRequired" : false,
                "code" : "code",
                "field" : "field",
                "messageInformation" : "messageInformation"
              } ],
              "tspRestorationPriority" : "tspRestorationPriority",
              "completionDate" : "2000-01-23T04:56:07.000+00:00",
              "expectedCompletionDate" : "2000-01-23T04:56:07.000+00:00",
              "orderDate" : "2000-01-23T04:56:07.000+00:00",
              "projectId" : "projectId"
            }"""

            when (exampleContentType) {
                "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
                "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
                else -> call.respondText(exampleContentString)
            }
        }
    }
            .apply {
                // TODO: ktor doesn't allow different authentication registrations for endpoints sharing the same path but different methods.
                //       It could be the authentication block is being abused here. Until this is resolved, swallow duplicate exceptions.

                try {
                    authentication {
                        oauthAtLocation<Paths.productOrderGet>(client, ApplicationExecutors.asCoroutineDispatcher(),
                                providerLookup = { ApplicationAuthProviders["bearer"] },
                                urlProvider = { currentLocation, provider ->
                                    // TODO: define a callback url here.
                                    "/"
                                })
                    }
                } catch (e: io.ktor.application.DuplicateApplicationFeatureException) {
                    application.environment.log.warn("authentication block for '/productOrderManagement/v3/productOrder/{ProductOrderId}' is duplicated in code. " +
                            "Generated endpoints may need to be merged under a 'route' entry.")
                }
            }
}
